name: SimpleChatquiz
author: TomBock
version: 1.0
api-version: '1.21'
main: com.bocktom.simplechatquiz.ChatquizPlugin
commands:
  chatquiz:
    description: Start or Stop a quiz
    usage: /chatquiz <start [Amount of questions]/stop/reload>
    permission: chatquiz.admin
permissions:
    chatquiz.admin:
      description: Allows someone to start and stop a Chatquiz
      default: op