name: PhoenixChatquiz
version: '1.7'
api-version: '1.21'
main: com.bocktom.ChatquizPlugin
commands:
  chatquiz:
    description: Start or Stop a quiz
    usage: /chatquiz <start|stop> [Fragenanzahl]
    permission: chatquiz.start
permissions:
    chatquiz.start:
      description: Allows someone to start and stop a Chatquiz